#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="zerotier-client"
source /assets/defaults/20-zerotier
source /assets/functions/20-zerotier
check_container_initialized

liftoff

print_start "Starting Zerotier One ${ZEROTIER_VERSION}"
silent exec s6-setuidgid "${CLIENT_USER}" zerotier-one ${CLIENT_ARGS}