#!/command/with-contenv bash

add_bash_completion() {
    cat <<EOF >> /root/.bashrc

## Zerotier Bash Completions
_zerotier_get_network_ids () {
        COMPREPLY=(\$(compgen -W "\$(ls -1 /var/lib/zerotier-one/networks.d | cut -c 1-16)" -- \${cur}))
}

_zerotier_get_network_ids_from_history () {
    COMPREPLY=(\$(compgen -W "\$(fc -l -1000 -1 | sed -n 's/.*\([[:xdigit:]]\{16\}\).*/\1/p')" -- \${cur}))
}

_zerotier_zerotier-cli_completions() {
    local cur prev

    cur=\${COMP_WORDS[COMP_CWORD]}
    prev=\${COMP_WORDS[COMP_CWORD-1]}

    case \${COMP_CWORD} in
        1)
            COMPREPLY=(\$(compgen -W "info listpeers peers listnetworks join leave set get listmoons orbit deorbit" -- \${cur}))
            ;;
        2)
            case \${prev} in
                leave)
                    _zerotier_get_network_ids
                ;;
                join)
                    _zerotier_get_network_ids_from_history
                ;;
                set)
                    _zerotier_get_network_ids
                ;;
                get)
                    _zerotier_get_network_ids
                ;;
                *)
                    COMPREPLY=()
                ;;
            esac
            ;;
        *)
            COMPREPLY=()
            ;;
    esac
}

complete -F _zerotier_zerotier-cli_completions zerotier-cli
##
EOF
}

bootstrap_filesystem() {
    case "${1}" in
        controller )
            if [ ! -d "${CONTROLLER_DATA_PATH}" ]; then
                mkdir -p "${CONTROLLER_DATA_PATH}"
            fi
            if [ "$(stat -c %U "${CONTROLLER_DATA_PATH}")" != "zerotier" ] ; then chown zerotier:zerotier "${CONTROLLER_DATA_PATH}" ; fi
            rm -rf /var/lib/zerotier-one
            ln -sf "${CONTROLLER_DATA_PATH}" /var/lib/zerotier-one
        ;;
        dns )
            mkdir -p /etc/coredns/
            chown -R coredns:zerotier /etc/coredns/
            if [ ! -d "${DNS_DATA_PATH}" ]; then
                mkdir -p "${DNS_DATA_PATH}"
            fi
            if [ "$(stat -c %U "${DNS_DATA_PATH}")" != "coredns" ] ; then chown coredns:zerotier "${DNS_DATA_PATH}" ; fi
        ;;
        logs )
            if [ ! -d "${LOG_PATH}" ]; then
                mkdir -p "${LOG_PATH}"
            fi
            if [ "$(stat -c %G "${LOG_PATH}")" != "zerotier" ] ; then chown -R zerotier:zerotier "${LOG_PATH}" ; fi
        ;;
        ui )
            :
        ;;
    esac
}


configure_controller() {
    if var_false "${CONTROLLER_ENABLE_METRICS}" ; then ln -sf /dev/null /var/lib/zerotier-one/metrics.prom ; fi
    for management_network in ${CONTROLLER_MANAGEMENT_NETWORKS//,/$IFS}; do
        management_networks=${management_networks}"\"${management_network}\","
    done
    management_networks=$(echo ${management_networks} | sed "s|,$||g")
    cat <<EOF > /var/lib/zerotier-one/local.conf
  {
    "settings": {
        "primaryPort": ${ZT_PRIMARY_PORT:-${CONTROLLER_LISTEN_PORT}},
        "portMappingEnabled": ${ZT_PORT_MAPPING_ENABLED:-${CONTROLLER_ENABLE_PORT_MAPPING,,}},
        "softwareUpdate": "disable",
        "allowManagementFrom": [${management_networks}],
        "allowTcpFallbackRelay": ${ZT_ALLOW_TCP_FALLBACK_RELAY:-${CONTROLLER_ALLOW_TCP_FALLBACK_RELAY,,}}
    }
  }
EOF
}

configure_dns() {
    sanity_var ZTNET_API_TOKEN "Personal + Org API Token from ZTNET"
    set -o posix ; set | grep -E '^(DNS_LISTEN_PORT=|LOG_PATH=|ZTNET_API_HOST=|ZTNET_AUTH_HEADER=|ZT_NETWORKS=)' > /etc/coredns/.env
    sed -i "s|^DNS_|COREDNS_|g" /etc/coredns/.env
    echo "${DNS_UPDATE_PERIOD} source /etc/coredns/.env ; s6-setuidgid ${COREDNS_USER} /usr/local/bin/ztnet-dns-companion --file >/dev/null 2>&1" >> /assets/cron/crontab.txt
}

configure_ui() {
    sanity_var UI_SITE_URL "Site URL eg https://example.com"

    sed -i "s|{{UI_LISTEN_PORT}}|${UI_LISTEN_PORT}|g" /etc/nginx/sites.enabled/${NGINX_SITE_ENABLED}.conf

    transform_file_var \
                        DB_HOST \
                        DB_NAME \
                        DB_PASS \
                        DB_PORT \
                        DB_USER

    if [ -n "${UI_DB_HOST}" ]; then DB_HOST=${DB_HOST:-${UI_DB_HOST}}; fi
    if [ -n "${UI_DB_NAME}" ]; then DB_NAME=${DB_NAME:-${UI_DB_NAME}}; fi
    if [ -n "${UI_DB_PASS}" ]; then DB_PASS=${DB_PASS:-${UI_DB_PASS}}; fi
    if [ -n "${UI_DB_PORT}" ]; then DB_PORT=${DB_PORT:-${UI_DB_PORT}}; fi
    if [ -n "${UI_DB_USER}" ]; then DB_USER=${DB_USER:-${UI_DB_USER}}; fi

    db_ready pgsql

    cat << EOF >> /app/.env
DATABASE_URL=postgresql://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public
ZT_ADDR=${ZT_ADDR}
NEXT_PUBLIC_APP_VERSION=${ZT_NET_VERSION}

EOF

    envFilename='.env.production'
    nextFolder='/app/.next/'

    cd /app
    print_info "[ui] Applying migrations to the database"
    silent npx prisma migrate deploy
    silent print_info "[ui] Migrations applied successfully"

    silent print_info "[ui] Seeding the database"
    silent npx prisma db seed
    silent print_info "[ui] Database seeded successfully"

    if [ -z "${UI_SECRET}" ]; then
        UI_SECRET=$(openssl rand -base64 32)
        print_warn "You should set a UI_SECRET environment variable to a secure value"
    fi

    echo "NEXTAUTH_URL=\"${UI_SITE_URL}\"" >> /app/.env
    echo "NEXT_PUBLIC_APP_VERSION=${ZTNET_VERSION}" >> /app/.env
    echo "PORT=${UI_LISTEN_PORT}" >> /app/.env
    echo "NEXTAUTH_SECRET=${UI_SECRET}" >> /app/.env
    echo "NEXT_PUBLIC_SITE_NAME=${UI_SITE_NAME}" >> /app/.env

    update_template /etc/nginx/sites.enabled/ztnet.conf HOSTNAME
}

setup_container_mode() {
    if [ -f "/tmp/.container/toi_zerotier/CONTAINER_MODE" ]; then
        print_debug "Importing MODE environment generated variables"
        source /tmp/.container/toi_zerotier/CONTAINER_MODE
    else
        mkdir -p /tmp/.container/toi_zerotier/
        modes=$(echo "${MODE}" | tr "," "\n")
        for mode in $modes ; do
            case "${mode,,}" in
                "controller" )
                    print_debug "Enabling Container Mode for: CONTROLLER"
                    echo "ENABLE_CONTROLLER=TRUE" >> /tmp/.container/toi_zerotier/CONTAINER_MODE
                ;;
                "dns" )
                    print_debug "Enabling Container Mode for: DNS"
                    echo "ENABLE_DNS=TRUE" >> /tmp/.container/toi_zerotier/CONTAINER_MODE
                ;;
                "ui" )
                    print_debug "Enabling Container Mode for: UI"
                    echo "ENABLE_UI=TRUE" >> /tmp/.container/toi_zerotier/CONTAINER_MODE
                ;;
                "standalone" | "manual" )
                    print_debug "Enabling Container Mode for: STANDALONE"
                    echo "ENABLE_STANDALONE=TRUE" >> /tmp/.container/toi_zerotier/CONTAINER_MODE
                ;;
                *)
                    print_error "Unknown 'MODE' environment variable - exitting.."
                    exit 1
                ;;
            esac
        done
        source /tmp/.container/toi_zerotier/CONTAINER_MODE
    fi
}

