#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service
SERVICE_NAME="zerotier"
setup_container_mode
bootstrap_filesystem logs
add_bash_completion

if [ ! -f "/tmp/.container/container-restart" ] ; then
    if var_true "${ENABLE_CLIENT}" ; then
        if var_true "${ENABLE_CONTROLLER}" ; then
            print_error "Can't have both MODE CONTROLLER and CLIENT at once"
            exit 1
        fi
        print_debug "Configuring Client"
        bootstrap_filesystem client
        configure_client
        case "${LOG_TYPE,,}" in
            file )
                create_logrotate zerotier-client "${LOG_PATH}"/"${CLIENT_LOG_FILE}" zerotier-client zerotier zerotier
            ;;
        esac
    else
        service_stop 20-client
    fi

    if var_true "${ENABLE_CONTROLLER}" ; then
            if var_true "${ENABLE_CLIENT}" ; then
            print_error "Can't have both MODE CONTROLLER and CLIENT at once"
            exit 1
        fi
        print_debug "Configuring Controller"
        bootstrap_filesystem controller
        configure_controller
        case "${LOG_TYPE,,}" in
            file )
                create_logrotate zerotier-controller "${LOG_PATH}"/"${CONTROLLER_LOG_FILE}" zerotier-controller zerotier zerotier
            ;;
        esac
    else
        service_stop 20-controller
    fi

    if var_true "${ENABLE_DNS}" ; then
        print_debug "Configuring DNS"
        bootstrap_filesystem dns
        grant_sudo "${DNS_USER}" /usr/sbin/zerotier-cli
        configure_dns
        case "${LOG_TYPE,,}" in
            file )
                create_logrotate coredns "${DNS_LOG_PATH}"/"${DNS_LOG_FILE}" coredns "${DNS_USER}" zerotier
            ;;
        esac
    else
        service_stop 20-dns
    fi

    if var_true "${ENABLE_UI}" ; then
        print_debug "Configuring UI"
        bootstrap_filesystem ui
        configure_ui
    else
        service_stop 10-nginx
        service_stop 20-ui
    fi

    if var_true "${ENABLE_STANDALONE}" ; then
        print_debug "Configuring Standlone"
        liftoff
        exit 0
    fi
fi

liftoff