#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="zt-net"
source /assets/defaults/20-zerotier
source /assets/functions/20-zerotier
check_container_initialized

export NEXTAUTH_URL_INTERNAL=http://localhost:${UI_LISTEN_PORT}
export NEXT_TELEMETRY_DISABLED=1
export NODE_ENV=production
if [ -z "${UI_CONTROLLER_URL}" ] ; then
    export ZT_ADDR=http://localhost:${CONTROLLER_LISTEN_PORT}
else
    export ZT_ADDR=${UI_CONTROLLER_URL}
fi

liftoff

print_start "Starting Zerotier UI ZT-Net ${ZTNET_UI_VERSION}"
cd /app

silent exec s6-setuidgid "${ZEROTIER_USER}" \
                                node server.js


