#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="coredns"
source /assets/defaults/20-zerotier
source /assets/functions/20-zerotier
check_container_initialized
setup_container_mode

liftoff

if var_true "${ENABLE_UI}" ; then
    while true; do
        if pgrep "next-server" > /dev/null; then
            break
        else
            sleep 1
        fi
    done
fi

print_start "Starting CoreDNS ${COREDNS_VERSION}"
sleep 1
s6-setuidgid ${COREDNS_USER} /usr/local/bin/ztnet-dns-companion --format coredns --file
s6-setuidgid ${COREDNS_USER} /usr/local/bin/ztnet-dns-companion --format hosts --file
exec s6-setuidgid "${COREDNS_USER}" coredns \
                                        -conf /etc/coredns/Corefile | ts -m '%Y-%m-%dT%H:%M.%S' >> ${DNS_LOG_PATH}/${DNS_LOG_FILE}