#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="coredns"
source /assets/defaults/20-zerotier
source /assets/functions/20-zerotier
check_container_initialized
setup_container_mode

liftoff

if var_true "${ENABLE_UI}" ; then
    while true; do
        if pgrep "next-server" > /dev/null; then
            break
        else
            sleep 1
        fi
    done
fi

sleep 1
s6-setuidgid ${DNS_USER} /usr/local/bin/ztnet-dns-companion --format coredns --file
if [ "${?}" = "0" ]; then
    s6-setuidgid ${DNS_USER} /usr/local/bin/ztnet-dns-companion --format hosts --file
fi

if [ -f /etc/coredns/Corefile ] ; then
    print_start "Starting CoreDNS ${COREDNS_VERSION}"
    exec s6-setuidgid "${DNS_USER}" coredns \
                                        -conf /etc/coredns/Corefile | ts -m '%Y-%m-%dT%H:%M.%S' >> ${DNS_LOG_PATH}/${DNS_LOG_FILE}

else
    print_error "No CoreDNS Configuration found, disabling DNS service"
    s6-svc -d /var/run/s6/legacy-services/20-dns
fi
