#!/command/with-contenv bash

source /assets/functions/00-container
PROCESS_NAME="zerotier-controller"
source /assets/defaults/10-zerotier
source /assets/functions/10-zerotier
check_container_initialized

liftoff

print_start "Starting Zerotier One ${ZEROTIER_VERSION}"
exec s6-setuidgid "${ZEROTIER_USER}" zerotier-one ${ZEROTIER_ARGS}