#!/command/with-contenv bash

source /assets/functions/00-container
SERVICE_NAME="zerotier-controller"
source /assets/defaults/20-zerotier
source /assets/functions/20-zerotier
check_container_initialized

liftoff

print_start "Starting Zerotier One ${ZEROTIER_VERSION}"
silent exec s6-setuidgid "${ZEROTIER_USER}" zerotier-one ${ZEROTIER_ARGS}